name: my-first-workflow
run-name: first-run
on: [push]

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Downloading repository
        uses: actions/checkout@v4
        
      - name: Setting up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: IP
        run: dig +short myip.opendns.com @resolver1.opendns.com

      - name: test
        run: sudo apt install cmatrix
      
      - name: Running NodeJS
        run: node /home/runner/work/file-test/file-test/server/index.js
